### PR TITLE
[PR] Fixes #16. Redesign the feature "New Model".

### LINKED ISSUE #16: Redesign the feature "New Model"
Redesign the feature "New Model" (main interface)
- [x] Specify the behavior and the design of GUI using low-fidelity prototypes
- [x] Review the specification
- [x] Refactor the source code to develop the changes and improvements defined by the specification

### User Storie
As a User, I WANT to create a new model SO THAT I can create simulations with the existing library files.

### General behavior
**Preconditions**: -
**Postconditions**: 
1) the new model (XML file) is created inside the project selected or created; 
2) the scripts folder is copied inside the project directory;
 3) the new model is opened in the editor (main interface); 
4) the corresponding project folder is expanded in the "Project Explorer View".

**Rules / restrictions:** 
- a name is valid if it contains only alphanumeric chars, hyphen (-) and/or underscore (_)
- a model must be inside a project

### Basic Flow
1. User access the "New Model" feature: File -> New Model | Toolbar icon | Control + N
2. "New Model" window is opened in the page to select the project. The next button is disabled when the window is loaded. Selection from the Project Explorer view is cleared.
4. The user selects the project which will contain the model
5. The "Next" button is enabled allowing the user to click or "ENTER" on the keyboard.
6. User click on "Next" or press "Enter" or "double click" on a project.
7. "New Model" page is loaded. All existing models of DengueME and user's personal libraries are presented.
8. User selects the model (a TerraME or R model). Then, user types a valid name (ID). 
9. The "Create" button is enabled (only if a model was selected and a valid name was specified).
10. User clicks on "Create" button or types "ENTER" on the keyboard.
11. The model (XML file) is created inside the selected project, with the name defined by user, and the model script folder is copied into the project folder. The "New Model" window is closed and the system returns to the main interface, with the model opened to be edited.

### Alternative Flow: user cancel the operation (project page or model page)
N.1. User clicks on "Cancel" or "X"
N.2. The "New Model" window is closed and the system returns to the main interface

### Alternative Flow: user clicks on "Previous" button (model page)
5.1. User clicks on "Previous" button.
5.2. The project page is reloaded with the selection in the same project already selected by user.

### Alternative Flow: name is invalid (model page)
6.1. User types an invalid name for the model.
6.2. A warning message is presented.

### Alternative Flow: name already exists (model page)
3.1. User types a name of a model that already exists in the same project.
3.2. A warning message is presented.

### Prototype
**Project Page**
image

**Model Page** 
Category: All selected.
image

### Guildelines
- The window is modal and opened with auto-focus
- After opening a new model window, the GUI must clear the selected itens on project view tree.
- When the project page is loaded, the default focus must be on the list of projects widget.
- When the model page is loaded, the default focus must be on the type of model widget.
- The "Next | Create" button has greater priority to receive focus than the "Cancel | Previous" button, which means that if everything is fine (e.g. model was selected and name is valid and unique) and user types "Enter", the "Next | Create" must be performed.

### Messages and labels (english | portuguese) 
(project page)
- Window Title: New Model | Novo Modelo
- Title: New Model | Novo Modelo
- Subtitle: Select the project of your new model. | Selecione o projeto do novo modelo.
- Labels:
    - Projects | Projetos
    - Choose the project in which the new model will be created. | Escolha o projeto no qual será criado o novo modelo.

(model page)
- Window Title: New Model | Novo Modelo
- Title (model page): New Model | Novo Modelo
- Subtitle (model page): Select a model and define its name. | Selecione o modelo e defina seu nome.
- Labels:
    - Category | Categoria
    - Models | Modelos
    - Description | Descrição
    - Name (ID) | Nome (ID)
    - Define a name (unique identifier) for your new model. | Defina um nome (identificador único) para o novo modelo.
- Warning (invalid name): The model name can contain only alphanumeric chars, hyphen (-) and / or underscore (\_) | O nome do modelo pode conter somente caracteres alfanuméricos, hífen (-) e / ou sublinhado (\_). 
- Warning (duplicated name): A model with this name already exists in current project. | Um modelo com esse nome já existe no projeto atual.

### PR DESCRIPTION
**Pull request by miguelspe**
This is the PR related to #16, it changes how the user can create a new model on DengueME interface.

Changes proposed in this pull request:
- Only two pages to create a new model.
- Project page contains validations and new ways to select a project (double click, enter ou clicking "Next Button" ).
- Users can select a category to filter the models' library (All, vector, transmission).
- The Model is shown by its name instead of by its id.
- When a user clicks on the model name a description related to the model is presented.
- Warning messages were added to model Name (ID).
- Tested on macOS Sierra (10.12.6) 

Closes #16

### CODE REVIEW

**Comment by tiagofml** [comment]
@Guelmisp Some problems that must be fixed:
- the window must be opened with auto-focus
- the validation of model's name (ID) is not working well. There are two problems: 
1) the GUI can lead users to be confused, e.g., the "teste22" project is currently selected in the Project Explorer View, but in the first page of the window, the "teste" project was selected. Then, if he types a name already used for a model it can be confusing. A suggestion is to REMOVE the first page (Project Page), using a single page, and then to use a dropdown (combobox) similar to the "Category" field, 
image
OR keep with two pages, but showing in Model Page which project was selected.
image
2) There is a problem with Name (ID) validation (duplicated name): it shows an error when it should not do it (teste2 is the name of a model available in the user's local models library). 
image
How to reproduce: 1) using the Model Builder, create a new model to your local library, 2) try to create a new model (File -> New Model) with the same Name (ID) used in the previous step. The restriction must be applied only to prevent creating a new file (model) with the same name of an existing one, inside the same project (folder). There is no reason to avoid using an equal name for two models if they are inside different projects (folders) or if the same name was used by a model of the library (DengueME Lib or user's lib).
3) Models of User's Library are not being presented. After copying the folder Models of DengueME Lib to the directory, the Model Page presented the existing models as expected. However, the models created by user with ModelBuilder were not presented.

**Review by tiagofml — CHANGES_REQUESTED** [review]
Some changes are required, please see the comments.

**Comment by miguelspe** [comment]
New Model new interface with the suggested change:

screen shot 2017-10-17 at 3 59 13 pm

**Comment by tiagofml** [comment]
@Guelmisp The model page has some problems: it is enabling the "Create" button when it should not be. 
- Case 1: how to reproduce: 1) Select a model, 2) Type an invalid name - the button will be disabled, 3) Click on some language (R or TerraME) in the box - the button remains disabled; 4) Type a valid name - the button will be enabled. However, none model is selected.
- Case 2: how to reproduce: 1) Select a model, 2) Type an invalid name - the button will be disabled, 3) Click on some language (R or TerraME), 4) Click on some model - the button will be enabled.
image

**Review by tiagofml — APPROVED** [review]

**Pull request merged**
